#端口号
server:
  port: 10010

#服务名称
spring:
  application:
    name: api-getway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true #ip优先，获取host时会获取到ip地址
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #在eureka中的实例id

#zull管理的网址前面要加api，起识别的作用，同时开启重试的功能
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/** # 将商品微服务映射到/item/**
    search-service: /search/** # 搜索的微服务
    user-service: /user/** #将用户微服务映射到user
    auth-service: /auth/** #将授权中心映射到auth路径下
    cart-service: /cart/** #购物车路径
    order-service: /order/**
  add-host-header: true #携带hosy本身的请求头信息
  sensitive-headers:  #敏感头设置为null
#负载均衡的设置
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

#熔断机制
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms
ly:
  jwt:
    pubKeyPath: H:/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/send
      - /api/item